[project]
name = "papermes-shared"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "manuelseeger", email = "mail@manuelseeger.de" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic-settings>=2.10.0",
    "pyyaml>=6.0.2",
    "truststore>=0.10.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
